### ISSUE TITLE
Invert plots in dark mode

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/papyros#131]
Maybe we could consider to invert plots (Matplotlib) in dark mode:

```css
img {
   -webkit-filter: invert(1);
   filter: invert(1);
}
```

turns

![image](https://user-images.githubusercontent.com/5736113/165274874-f92a5578-62b7-42dd-a024-02e1d9362376.png)

into

![image](https://user-images.githubusercontent.com/5736113/165274981-1c8ab55c-4de1-4322-a0c1-1a370cefdd82.png)
